# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  test-react:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test
      - codecov/upload:
          file: "coverage/coverage-final.json"

  test-server:
    docker:
      - image: circleci/python:3.7.3

    # Set Working directory
    working_directory: ~/repo/playlist

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 playlist/manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

deploy:
  docker:
    - image: circleci/node:7.10

  working_directory: ~/repo

  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

    - run: npm install

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: Build react page
        command: npm run build
    - run:
        name: Copy Build folder to server static folder
        command: |
          rm -R ./playlist/frontend/build
          cp ./build ./playlist/frontend/build
    - run:
        name: Commit build
        command: git add .

workflows:
  version: 2.1
  test_react_django:
    jobs:
      - test-server
      - test-react
        # requires:
        #   - test-server
      - deploy:
          requires:
            - test-server
            - test-react
