#
#  CircleCI 2.0 configuration file with Node and Python
#
version: 2.1

jobs:
  test-react:
    docker:
      - image: circleci/node:7.10
        environment:
          CODECLIMATE_REPO_TOKEN: 0d48f6d1d4eccb4397f928c0d69485f389357a28de8fcbe4abca4cea9971f8df
          CI: true

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: npm install
          command: |
            npm install
            sudo npm install -g codeclimate-test-reporter

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Chown repo
          command: sudo chown -R circleci:circleci ~/repo/*

      - run:
          name: Test
          command: npm run test

      - run:
          name: Upload Results
          command: codeclimate-test-reporter < coverage/lcov.info

  # BRNCE INNEN NÉZD
  test-server:
    docker:
      - image: circleci/python:3.7.3

    # Set Working directory
    working_directory: ~/repo/playlist

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pipenv
            pipenv install
      - save_cache:
          key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pipenv run python3 playlist/manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

  deploy:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      #- run:
      #name: Build react page
      #command: |
      #npm run build
      # - run:
      #     name: Copy Build folder to server static folder
      #     command: |
      #       rm -R ./playlist/frontend/build
      #       cp ./build ./playlist/frontend/build
      # - run:
      #     name: Commit build
      #     command: git add .

workflows:
  version: 2.1
  playlist_ci:
    jobs:
      - test-server
      - test-react
      - deploy:
          requires:
            - test-server
            - test-react
