# Generated by Django 2.2.3 on 2019-07-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
