# Generated by Django 2.2.3 on 2019-07-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='user',
            field=models.CharField(max_length=36),
        ),
    ]
