# Generated by Django 2.2.3 on 2019-07-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_blockedsong_blockeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='yttitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
