# Generated by Django 2.2.4 on 2019-09-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20190907_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AlterModelOptions(
            name='blockeduser',
            options={'permissions': [('can_ban', 'Tud un/bannolni')]},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'permissions': [('can_modify_settings', 'Tud állítani a beállításokon')]},
        ),
        migrations.AlterField(
            model_name='log',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
